name: coachsplit
description: CoachSplit - mobile Zeitmessung und Analyse für Trainer.
publish_to: 'none'

version: 1.0.6+23
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  sembast: ^3.8.9+1
  sembast_web: ^2.4.0+4
  path: ^1.9.0
  uuid: ^4.5.3
  http: ^1.2.2
  qr_flutter: ^4.1.0
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/coachsplit_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/coachsplit_icon.png"
    background_color: "#0B1118"
    theme_color: "#0B1118"
  image_path: "assets/icon/coachsplit_icon.png"
  adaptive_icon_background: "#0B1118"
  adaptive_icon_foreground: "assets/icon/coachsplit_icon.png"
